name: Develop Branch Action

# todo: add container vulnerability scan

on:
  pull_request_target:
    types: [opened]
    branches:
      - develop
  workflow_dispatch:    

jobs:
  dev-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: helm_results
        files: "charts/linkerd"         

    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: helm_results.sarif  
        category: "Kubescape scan for Helm Charts"

    - name: Moving scan results to appropriate folders
      run: |
        TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
        echo "Moving helm_results.sarif to reports/kubernetes-nsa-cisa-yaml-scan-analysis/helm_results_${TIMESTAMP}.sarif"
        mv -f "helm_results.sarif" "reports/kubernetes-nsa-cisa-yaml-scan-analysis/helm_results_${TIMESTAMP}.sarif"


    - name: Push changes to our repository
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git pull origin
        git add charts/*
        git add reports/*
        git commit -m "added charts and scan results"
        echo ${{ github.head_ref }}
        git push origin ${{ github.head_ref }}