name: Install/Upgrade 

on:
  repository_dispatch:
    types: [install_unoplat_service_mesh]
  workflow_dispatch: 

jobs:
  install_civo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0 

    - uses: azure/setup-kubectl@v3
      id: install    


    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1


    - uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Print payload
      env:
        MESSAGE: ${{ github.event.client_payload.message }}
      run: echo $MESSAGE


    - name: Install jq
      run: sudo apt-get install jq

    - name: Add Helm repo
      run: helm repo add unoplat-service-mesh-linkerd https://unoplat.github.io/unoplat-service-mesh-linkerd

    - name: Update Helm repo
      run: helm repo update

    - name: Install latest pre-release version
      env:
        ROOT_CRT: ${{ secrets.ROOT_CRT }}
        DECRYPTED_ISSUER_KEY: ${{ secrets.DECRYPTED_ISSUER_KEY }}
        ISSUER_CRT: ${{ secrets.ISSUER_CERT }}
      run: |
        echo "$ROOT_CRT" > root.crt
        echo "$DECRYPTED_ISSUER_KEY" > decrypted_issuer.key
        echo "$ISSUER_CRT" > issuer.crt
        version=$(helm search repo unoplat-service-mesh-linkerd/linkerd-control-plane --versions --devel --output json | jq -r '.[0].version')
        helm install linkerd-crds linkerd/linkerd-crds -n unoplat-service-mesh --version 1.8.0
        helm upgrade --install linkerd --namespace unoplat-service-mesh unoplat-service-mesh-linkerd/linkerd-control-plane --set-file identityTrustAnchorsPEM=root.crt --set-file identity.issuer.tls.crtPEM=issuer.crt --set-file identity.issuer.tls.keyPEM=decrypted_issuer.key --set cniEnabled=false --version $version --devel --create-namespace